import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import styles from "../Portfolio.module.css";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const Portfolio = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const data = location.state;

  if (!data) {
    return (
      <div className={styles.noData}>
        <h2>No data found</h2>
        <button onClick={() => navigate("/registration")} className={styles.backBtn}>
          Go to Registration
        </button>
      </div>
    );
  }

  const { personal, education, skills, experience, colors, portfolioType } = data;
  const c = colors || { primary: "#6c3baa", secondary: "#8b5cf6", background: "#0f0c29", textColor: "#ffffff" };

  const downloadPDF = async () => {
    const btn = document.getElementById("downloadBtn");
    if (btn) btn.style.display = "none";
    const el = document.getElementById("portfolioBox");
    const canvas = await html2canvas(el, { scale: 2, backgroundColor: "#ffffff" });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "pt", "a4");
    const imgProps = pdf.getImageProperties(imgData);
    const pw = pdf.internal.pageSize.getWidth();
    const ph = (imgProps.height * pw) / imgProps.width;
    pdf.addImage(imgData, "PNG", 0, 0, pw, ph);
    pdf.save("portfolio.pdf");
    if (btn) btn.style.display = "block";
  };

  // ── ATS Resume Template ──
  if (portfolioType === "ats") {
    return (
      <div className={styles.atsPage}>
        <div className={styles.atsBox} id="portfolioBox">
          <div style={{ textAlign: "right", marginBottom: 10 }}>
            <button id="downloadBtn" className={styles.downloadBtn} onClick={downloadPDF}>
              Download PDF
            </button>
          </div>
          <div className={styles.atsHeader}>
            <h1>{personal.name || "Your Name"}</h1>
            <p>{personal.email} | {personal.contact} | {personal.gender} | Age: {personal.age}</p>
            {personal.field && <p><strong>Field:</strong> {personal.field}</p>}
          </div>
          {personal.objective && (
            <>
              <div className={styles.atsSection}>
                <h2>Objective</h2>
                <p>{personal.objective}</p>
              </div>
            </>
          )}
          <hr className={styles.atsHr} />
          <div className={styles.atsSection}>
            <h2>Education</h2>
            {education.map((edu, i) => (
              <div key={i} className={styles.atsItem}>
                <strong>{edu.level}</strong> — {edu.institute} ({edu.year}){edu.marks ? ` | Marks: ${edu.marks}` : ""}
              </div>
            ))}
          </div>
          <div className={styles.atsSection}>
            <h2>Skills</h2>
            <p>{skills.join(", ")}</p>
          </div>
          {experience.length > 0 && (
            <div className={styles.atsSection}>
              <h2>Experience</h2>
              {experience.map((exp, i) => (
                <div key={i} className={styles.atsItem}>
                  <strong>{exp.role}</strong> at {exp.company} ({exp.duration})
                </div>
              ))}
            </div>
          )}
          <div className={styles.atsFooter}>ATS-Friendly Resume — Generated by Portfolio Maker</div>
        </div>
      </div>
    );
  }

  // ── Standard Portfolio Template (with dynamic colors) ──
  const s = {
    primary: c.primary,
    secondary: c.secondary,
    bg: c.background,
    text: c.textColor,
    lightBg: c.background + "15",
  };

  return (
    <div className={styles.portfolioPage} style={{ background: `linear-gradient(to bottom, ${s.bg}, ${s.secondary}, ${s.bg})` }}>
      <div style={{ width: "794px", margin: "0 auto" }}>
        <div className={styles.portfolioBox} id="portfolioBox" style={{ background: "#fff" }}>
        <div className={styles.portfolioHeader}>
          <h1 className={styles.portfolioTitle} style={{ color: s.primary }}>Portfolio</h1>
          <button id="downloadBtn" className={styles.downloadBtn} onClick={downloadPDF}
            style={{ background: s.secondary }}>
            Download PDF
          </button>
        </div>

        <div className={styles.profileRow}>
          {personal.picture && (
            <div className={styles.profileImg}>
              <img src={personal.picture} alt="Profile" style={{ border: `3px solid ${s.primary}` }} />
            </div>
          )}
          <div className={styles.profileInfo}>
            <h2 style={{ color: s.primary }}>{personal.name}</h2>
            <p>Email: {personal.email}</p>
            {personal.contact && <p>Contact: {personal.contact}</p>}
            <p>Age: {personal.age}</p>
            <p>Gender: {personal.gender}</p>
            {personal.field && <p>Field: {personal.field}</p>}
          </div>
        </div>

        {personal.objective && (
          <div className={styles.section}>
            <h3 style={{ color: s.primary, borderBottom: `2px solid ${s.secondary}` }}>Objective</h3>
            <p style={{ fontSize: "0.9rem", lineHeight: "1.6", color: "#333" }}>{personal.objective}</p>
          </div>
        )}

        <div className={styles.section}>
          <h3 style={{ color: s.primary, borderBottom: `2px solid ${s.secondary}` }}>Education</h3>
          <div className={styles.tableWrap}>
            <table className={styles.table}>
              <thead><tr>
                <th style={{ background: s.primary }}>Level</th>
                <th style={{ background: s.primary }}>Institute</th>
                <th style={{ background: s.primary }}>Year</th>
                <th style={{ background: s.primary }}>Marks/GPA</th>
              </tr></thead>
              <tbody>
                {education.map((item, i) => (
                  <tr key={i}>
                    <td>{item.level}</td>
                    <td>{item.institute}</td>
                    <td>{item.year}</td>
                    <td>{item.marks || "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className={styles.section}>
          <h3 style={{ color: s.primary, borderBottom: `2px solid ${s.secondary}` }}>Skills</h3>
          <ul className={styles.skillsList}>
            {skills.map((skill, i) => (
              <li key={i}>{skill}</li>
            ))}
          </ul>
        </div>

        {experience.length > 0 && (
          <div className={styles.section}>
            <h3 style={{ color: s.primary, borderBottom: `2px solid ${s.secondary}` }}>Experience</h3>
            <div className={styles.tableWrap}>
              <table className={styles.table}>
                <thead><tr>
                  <th style={{ background: s.primary }}>Company</th>
                  <th style={{ background: s.primary }}>Role</th>
                  <th style={{ background: s.primary }}>Duration</th>
                </tr></thead>
                <tbody>
                  {experience.map((item, i) => (
                    <tr key={i}>
                      <td>{item.company}</td>
                      <td>{item.role}</td>
                      <td>{item.duration}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        <div style={{ textAlign: "center", marginTop: "1.5rem", color: s.secondary, fontSize: "0.85rem" }}>
          Generated by Portfolio Maker
        </div>
        </div>
      </div>
    </div>
  );
};

export default Portfolio;
